In [2]:
%pip install pandas openpyxl

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 54.5 MB/s  0:00:00
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 59.5 MB/s  0:00:006m0:00:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: numpy, et-xmlfile, pandas, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/4 [numpy]  WARNING: The scripts f2py and numpy-config are installed in '/usr/local/python/3.12.1/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [openpyxl]3/4 [openpyxl]e]
Successfully installed et-xmlfile-2.0.0 numpy-2.4.4 openpyxl-3.1.5 pandas-3.0.2

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Inspect en Valideer 'Book1 (1).xlsx'
Dit notebook wordt gebruikt om de inhoud van het Excel-bestand `Tijdelijke Bestanden/Book1 (1).xlsx` te inspecteren en te valideren.

## 1. Importeer Vereiste Bibliotheken
We importeren `pandas` voor data-analyse en `os` voor padbeheer.

In [3]:
import pandas as pd
import os

print("Bibliotheken geladen.")

Bibliotheken geladen.

## 2. Definieer Bestandspad en Controleer Bestaan
We definiëren het pad naar het bestand en controleren of het toegankelijk is.

In [4]:
file_path = 'Tijdelijke Bestanden/Book1 (1).xlsx'
if os.path.exists(file_path):
    print(f"Bestand gevonden: {file_path}")
else:
    print(f"FOUT: Bestand niet gevonden op {file_path}")

Bestand gevonden: Tijdelijke Bestanden/Book1 (1).xlsx

## 3. Laad Excel Bestand in DataFrame
We laden de gegevens met de `openpyxl` engine. (We proberen de benodigde packages te installeren indien ze ontbreken).

In [5]:
try:
    df = pd.read_excel(file_path, engine='openpyxl')
    print("Gegevens succesvol geladen.")
except Exception as e:
    print(f"Fout bij laden: {e}")
    print("Probeer 'pip install pandas openpyxl' in de terminal.")

Gegevens succesvol geladen.

## 4. Inspecteer Datastructuur en Typen
We bekijken de kolommen en de eerste rijen.

In [6]:
print("--- Info ---")
print(df.info())
print("\n--- Eerste 5 rijen ---")
display(df.head())

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   168 non-null    object
 2   Unnamed: 2   168 non-null    object
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   169 non-null    object
 5   Unnamed: 5   168 non-null    object
 6   Unnamed: 6   169 non-null    str
 7   Unnamed: 7   20 non-null     object
 8   Unnamed: 8   127 non-null    str
 9   Unnamed: 9   127 non-null    str
 10  Unnamed: 10  168 non-null    str
 11  Unnamed: 11  168 non-null    str
 12  Unnamed: 12  35 non-null     str
 13  Unnamed: 13  21 non-null     str
 14  Unnamed: 14  168 non-null    object
 15  Unnamed: 15  168 non-null    object
 16  Unnamed: 16  168 non-null    object
 17  Unnamed: 17  1 non-null      str
dtypes: float64(2), object(8), str(8)
memory usage: 24.5+ KB
None

--- Eerste 5 rijen ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,40BM01,NaN,Printdatum:,2026-02-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 5. Controleer op Ontbrekende Waarden
We tellen het aantal null-waarden per kolom.

In [7]:
print("--- Ontbrekende waarden ---")
print(df.isnull().sum())

--- Ontbrekende waarden ---
Unnamed: 0     173
Unnamed: 1       5
Unnamed: 2       5
Unnamed: 3     173
Unnamed: 4       4
Unnamed: 5       5
Unnamed: 6       4
Unnamed: 7     153
Unnamed: 8      46
Unnamed: 9      46
Unnamed: 10      5
Unnamed: 11      5
Unnamed: 12    138
Unnamed: 13    152
Unnamed: 14      5
Unnamed: 15      5
Unnamed: 16      5
Unnamed: 17    172
dtype: int64

## 6. Genereer Samenvattende Statistieken
Statistische metrieken zoals gemiddelde $\mu$ en standaardafwijking $\sigma$ voor numerieke kolommen.

In [8]:
print("--- Statistieken ---")
display(df.describe())

--- Statistieken ---

       Unnamed: 0  Unnamed: 3
count         0.0         0.0
mean          NaN         NaN
std           NaN         NaN
min           NaN         NaN
25%           NaN         NaN
50%           NaN         NaN
75%           NaN         NaN
max           NaN         NaN

## 7. Gegevensvalidatie en Kwaliteitscontroles
We voeren specifieke controles uit, zoals het controleren op unieke waarden.

In [9]:
# Voorbeeld: Controleer of de eerste kolom uniek is (vaak een ID of Lotnummer)
if not df.empty:
    first_col = df.columns[0]
    is_unique = df[first_col].is_unique
    print(f"Is de kolom '{first_col}' uniek? {is_unique}")
    if not is_unique:
        print(f"Aantal duplicaten: {df[first_col].duplicated().sum()}")

Is de kolom 'Unnamed: 0' uniek? False
Aantal duplicaten: 172

In [10]:
# Toon de eerste 20 rijen van relevante kolommen (Unnamed: 1 t/m Unnamed: 16)
display(df.iloc[:20, 1:17])

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,40BM01,NaN,Printdatum:,2026-02-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,TBV opmaak,Tbv Opmaak II,NaN,datum,Week,order,PO Text,Project,Project Desc,Manufactured Item,Item Desc,code,Drawing,Plan,to do,Gewikkeld
6,0,0,NaN,2026-03-13 22:00:00,11,N20024349,NaN,40M002051,Hanab Brightlands Campus Noord,40M002051ADSTESS0C002K0BCCSX0,Adaptor 100 EST25 CSFB,A2A3,NaN,3,3,0
7,0,0,NaN,2026-04-03 05:14:34,14,N20024388,NaN,NaN,NaN,ADSTESS0C002K0BCCSX0,Adaptor 100 EST25 CSFB,NaN,NaN,10,10,0
8,0,1,NaN,2026-01-30 21:00:00,5,N20023991,buisstukken laten zagen in de spoolbouw\n,40M002015,MVOI 2026,ADSTESS0E002A0BCCSX0,Adaptor 150 EST20 CSFB,NaN,NaN,10,9,1
9,0,0,NaN,2026-03-13 22:00:00,11,N20024351,buis laten zagen in de spoolbouw\n,40M002051,Hanab Brightlands Campus Noord,40M002051ADSTESS0F001M0BCCSX0,Adaptor 200 EST16 CSFB,A2A3,NaN,4,4,0
10,0,0,NaN,2026-03-06 21:00:00,10,N20024264,"deze week maken, buis laten zagen in de spoolb...",40M002008,qualm 2026,40M002008ADSTESS0H002A0BCCSX0,Adaptor 250 EST20 CSFB,A1M6,NaN,4,4,0
11,0,0,NaN,2026-03-13 22:00:00,11,N20024354,buis laten zagen in de spoolbouw\n,40M001959,Geerdink 2026,ADSTESS0J001M0BCCSX0,Adaptor 350 EST16 CSFB,NaN,NaN,4,4,0
12,0,0,NaN,2026-03-20 22:00:00,12,N20024355,NaN,40M001959,Geerdink 2026,ADSTESS0J001M0BCCSX0,Adaptor 350 EST16 CSFB,NaN,NaN,6,6,0
13,0,0,NaN,2026-03-27 22:00:00,13,N20024356,NaN,NaN,NaN,ADSTESS0J001M0BCCSX0,Adaptor 350 EST16 CSFB,NaN,NaN,6,6,0
14,0,0,NaN,2026-03-06 21:00:00,10,N20024301,NaN,40M002050,Crossbridge,COSTCSS0C003E0BCCBB0,Coupler 100 CST32 CBCB,NaN,NaN,10,10,0
15,0,0,NaN,2026-02-20 21:00:00,8,N20024010,NaN,40M001960,Orys Tambourfiltrants addtions,40M001834COSTEFS0C001M0BCCJJ0,Coupler 100 EDF16 TBTB,A2G3,NaN,9,9,0
16,0,1,NaN,2026-02-13 21:00:00,7,N20024392,NaN,40M002048,Boccard Training CB TB Lam,COSTESS0C002K0BCCJJ0,Coupler 100 EST25 TBTB,NaN,NaN,5,5,0
17,0,0,NaN,2026-03-06 21:00:00,10,N20024334,NaN,NaN,NaN,COSTESS0C002K0BCCJJ0,Coupler 100 EST25 TBTB,NaN,NaN,10,10,0
18,0,0,NaN,2026-03-06 21:00:00,10,N20024302,NaN,40M002050,Crossbridge,COSTCSS0E003E0BCCBB0,Coupler 150 CST32 CBCB,NaN,NaN,10,10,0
19,0,1,NaN,2026-02-13 21:00:00,7,N20024008,NaN,40M001960,Orys Tambourfiltrants addtions,40M001834COSTEFS0E001M0BCCJJ0,Coupler 150 EDF16 TBTB,A2G3,NaN,10,8,2

In [11]:
# Print de waarden van de eerste 10 rijen voor een subset van de kolommen om de structuur te begrijpen
print(df.iloc[:10, 1:10].to_string())

   Unnamed: 1     Unnamed: 2  Unnamed: 3           Unnamed: 4 Unnamed: 5   Unnamed: 6                                 Unnamed: 7 Unnamed: 8                      Unnamed: 9
0         NaN            NaN         NaN                  NaN        NaN          NaN                                        NaN        NaN                             NaN
1         NaN            NaN         NaN                  NaN        NaN          NaN                                        NaN        NaN                             NaN
2         NaN            NaN         NaN                  NaN        NaN          NaN                                        NaN        NaN                             NaN
3         NaN            NaN         NaN                  NaN        NaN          NaN                                        NaN        NaN                             NaN
4         NaN            NaN         NaN               40BM01        NaN  Printdatum:                        2026-02-19 00:00:00        NaN                             NaN
5  TBV opmaak  Tbv Opmaak II         NaN                datum       Week        order                                    PO Text    Project                    Project Desc
6           0              0         NaN  2026-03-13 22:00:00         11    N20024349                                        NaN  40M002051  Hanab Brightlands Campus Noord
7           0              0         NaN  2026-04-03 05:14:34         14    N20024388                                        NaN        NaN                             NaN
8           0              1         NaN  2026-01-30 21:00:00          5    N20023991  buisstukken laten zagen in de spoolbouw\n  40M002015                       MVOI 2026
9           0              0         NaN  2026-03-13 22:00:00         11    N20024351         buis laten zagen in de spoolbouw\n  40M002051  Hanab Brightlands Campus Noord

In [12]:
# Print slechts de eerste 3 rijen om de headers/inhoud te zien
for i in range(3):
    print(f"Rij {i}: {df.iloc[i, 1:17].tolist()}")

Rij 0: [nan, nan, np.float64(nan), nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Rij 1: [nan, nan, np.float64(nan), nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Rij 2: [nan, nan, np.float64(nan), nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [13]:
# Zoek de eerste rij die NIET alleen uit NaN bestaat
non_empty_rows = df.dropna(how='all', subset=df.columns[1:17])
if not non_empty_rows.empty:
    print(f"Eerste niet-lege rij index: {non_empty_rows.index[0]}")
    print(f"Inhoud: {non_empty_rows.iloc[0, 1:17].tolist()}")
else:
    print("Geen niet-lege rijen gevonden in de opgegeven kolommen.")

Eerste niet-lege rij index: 4
Inhoud: [nan, nan, np.float64(nan), '40BM01', nan, 'Printdatum:', datetime.datetime(2026, 2, 19, 0, 0), nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [14]:
# Toon rijen 4 t/m 15 om de tabelstructuur te zien
display(df.iloc[4:15, 1:17])

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
4,NaN,NaN,NaN,40BM01,NaN,Printdatum:,2026-02-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,TBV opmaak,Tbv Opmaak II,NaN,datum,Week,order,PO Text,Project,Project Desc,Manufactured Item,Item Desc,code,Drawing,Plan,to do,Gewikkeld
6,0,0,NaN,2026-03-13 22:00:00,11,N20024349,NaN,40M002051,Hanab Brightlands Campus Noord,40M002051ADSTESS0C002K0BCCSX0,Adaptor 100 EST25 CSFB,A2A3,NaN,3,3,0
7,0,0,NaN,2026-04-03 05:14:34,14,N20024388,NaN,NaN,NaN,ADSTESS0C002K0BCCSX0,Adaptor 100 EST25 CSFB,NaN,NaN,10,10,0
8,0,1,NaN,2026-01-30 21:00:00,5,N20023991,buisstukken laten zagen in de spoolbouw\n,40M002015,MVOI 2026,ADSTESS0E002A0BCCSX0,Adaptor 150 EST20 CSFB,NaN,NaN,10,9,1
9,0,0,NaN,2026-03-13 22:00:00,11,N20024351,buis laten zagen in de spoolbouw\n,40M002051,Hanab Brightlands Campus Noord,40M002051ADSTESS0F001M0BCCSX0,Adaptor 200 EST16 CSFB,A2A3,NaN,4,4,0
10,0,0,NaN,2026-03-06 21:00:00,10,N20024264,"deze week maken, buis laten zagen in de spoolb...",40M002008,qualm 2026,40M002008ADSTESS0H002A0BCCSX0,Adaptor 250 EST20 CSFB,A1M6,NaN,4,4,0
11,0,0,NaN,2026-03-13 22:00:00,11,N20024354,buis laten zagen in de spoolbouw\n,40M001959,Geerdink 2026,ADSTESS0J001M0BCCSX0,Adaptor 350 EST16 CSFB,NaN,NaN,4,4,0
12,0,0,NaN,2026-03-20 22:00:00,12,N20024355,NaN,40M001959,Geerdink 2026,ADSTESS0J001M0BCCSX0,Adaptor 350 EST16 CSFB,NaN,NaN,6,6,0
13,0,0,NaN,2026-03-27 22:00:00,13,N20024356,NaN,NaN,NaN,ADSTESS0J001M0BCCSX0,Adaptor 350 EST16 CSFB,NaN,NaN,6,6,0
14,0,0,NaN,2026-03-06 21:00:00,10,N20024301,NaN,40M002050,Crossbridge,COSTCSS0C003E0BCCBB0,Coupler 100 CST32 CBCB,NaN,NaN,10,10,0

In [15]:
# Print rijen 4 t/m 10 om de inhoud te zien zonder dat het wordt afgebroken
for i in range(4, 11):
    print(f"Rij {i}: {df.iloc[i, 1:17].tolist()}")

Rij 4: [nan, nan, np.float64(nan), '40BM01', nan, 'Printdatum:', datetime.datetime(2026, 2, 19, 0, 0), nan, nan, nan, nan, nan, nan, nan, nan, nan]
Rij 5: ['TBV opmaak', 'Tbv Opmaak II', np.float64(nan), 'datum', 'Week', 'order', 'PO Text', 'Project', 'Project Desc', 'Manufactured Item', 'Item Desc', 'code', 'Drawing', 'Plan', 'to do', 'Gewikkeld']
Rij 6: [0, 0, np.float64(nan), datetime.datetime(2026, 3, 13, 22, 0), 11, 'N20024349', nan, '40M002051', 'Hanab Brightlands Campus Noord', '40M002051ADSTESS0C002K0BCCSX0', 'Adaptor 100 EST25 CSFB', 'A2A3', nan, 3, 3, 0]
Rij 7: [0, 0, np.float64(nan), datetime.datetime(2026, 4, 3, 5, 14, 34), 14, 'N20024388', nan, nan, nan, 'ADSTESS0C002K0BCCSX0', 'Adaptor 100 EST25 CSFB', nan, nan, 10, 10, 0]
Rij 8: [0, 1, np.float64(nan), datetime.datetime(2026, 1, 30, 21, 0), 5, 'N20023991', 'buisstukken laten zagen in de spoolbouw\n', '40M002015', 'MVOI 2026', 'ADSTESS0E002A0BCCSX0', 'Adaptor 150 EST20 CSFB', nan, nan, 10, 9, 1]
Rij 9: [0, 0, np.float64(nan), datetime.datetime(2026, 3, 13, 22, 0), 11, 'N20024351', 'buis laten zagen in de spoolbouw\n', '40M002051', 'Hanab Brightlands Campus Noord', '40M002051ADSTESS0F001M0BCCSX0', 'Adaptor 200 EST16 CSFB', 'A2A3', nan, 4, 4, 0]
Rij 10: [0, 0, np.float64(nan), datetime.datetime(2026, 3, 6, 21, 0), 10, 'N20024264', 'deze week maken, buis laten zagen in de spoolbouw\n', '40M002008', 'qualm 2026', '40M002008ADSTESS0H002A0BCCSX0', 'Adaptor 250 EST20 CSFB', 'A1M6', nan, 4, 4, 0]